export interface SurahContent {
    id: number;
    name: string;
    meaning: string;
    verses: number;
}

export const SURAH_LIST: SurahContent[] = [
    { id: 1, name: "Fatiha", meaning: "Açılış", verses: 7 },
    { id: 2, name: "Bakara", meaning: "İnek", verses: 286 },
    { id: 3, name: "Âl-i İmrân", meaning: "İmran Ailesi", verses: 200 },
    { id: 4, name: "Nisâ", meaning: "Kadınlar", verses: 176 },
    { id: 5, name: "Mâide", meaning: "Sofra", verses: 120 },
    { id: 6, name: "En'âm", meaning: "Davar", verses: 165 },
    { id: 7, name: "A'râf", meaning: "A'raf", verses: 206 },
    { id: 8, name: "Enfâl", meaning: "Ganimetler", verses: 75 },
    { id: 9, name: "Tevbe", meaning: "Tövbe", verses: 129 },
    { id: 10, name: "Yûnus", meaning: "Yunus Peygamber", verses: 109 },
    { id: 11, name: "Hûd", meaning: "Hud Peygamber", verses: 123 },
    { id: 12, name: "Yûsuf", meaning: "Yusuf Peygamber", verses: 111 },
    { id: 13, name: "Ra'd", meaning: "Gök Gürültüsü", verses: 43 },
    { id: 14, name: "İbrâhîm", meaning: "İbrahim Peygamber", verses: 52 },
    { id: 15, name: "Hicr", meaning: "Hicr Vadisi", verses: 99 },
    { id: 16, name: "Nahl", meaning: "Arı", verses: 128 },
    { id: 17, name: "İsrâ", meaning: "Gece Yürüyüşü", verses: 111 },
    { id: 18, name: "Kehf", meaning: "Mağara", verses: 110 },
    { id: 19, name: "Meryem", meaning: "Hz. Meryem", verses: 98 },
    { id: 20, name: "Tâhâ", meaning: "Ta-Ha", verses: 135 },
    { id: 21, name: "Enbiyâ", meaning: "Peygamberler", verses: 112 },
    { id: 22, name: "Hac", meaning: "Hac İbadeti", verses: 78 },
    { id: 23, name: "Mü'minûn", meaning: "Müminler", verses: 118 },
    { id: 24, name: "Nûr", meaning: "Işık", verses: 64 },
    { id: 25, name: "Furkân", meaning: "Hakkı Batıldan Ayıran", verses: 77 },
    { id: 26, name: "Şuarâ", meaning: "Şairler", verses: 227 },
    { id: 27, name: "Neml", meaning: "Karınca", verses: 93 },
    { id: 28, name: "Kasas", meaning: "Kıssalar", verses: 88 },
    { id: 29, name: "Ankebût", meaning: "Örümcek", verses: 69 },
    { id: 30, name: "Rûm", meaning: "Rumlular", verses: 60 },
    { id: 31, name: "Lokmân", meaning: "Lokman", verses: 34 },
    { id: 32, name: "Secde", meaning: "Secde", verses: 30 },
    { id: 33, name: "Ahzâb", meaning: "Gruplar", verses: 73 },
    { id: 34, name: "Sebe'", meaning: "Sebe Halkı", verses: 54 },
    { id: 35, name: "Fâtır", meaning: "Yaratan", verses: 45 },
    { id: 36, name: "Yâsîn", meaning: "Ya-Sin", verses: 83 },
    { id: 37, name: "Sâffât", meaning: "Sıra Sıra Duranlar", verses: 182 },
    { id: 38, name: "Sâd", meaning: "Sad", verses: 88 },
    { id: 39, name: "Zümer", meaning: "Zümreler", verses: 75 },
    { id: 40, name: "Mü'min", meaning: "İnanan", verses: 85 },
    { id: 41, name: "Fussilet", meaning: "Genişçe Açıklanmış", verses: 54 },
    { id: 42, name: "Şûrâ", meaning: "Danışma", verses: 53 },
    { id: 43, name: "Zuhruf", meaning: "Yaldız, Süs", verses: 89 },
    { id: 44, name: "Duhân", meaning: "Duman", verses: 59 },
    { id: 45, name: "Câsiye", meaning: "Diz Üstü Çökmek", verses: 37 },
    { id: 46, name: "Ahkâf", meaning: "Kum Tepeleri", verses: 35 },
    { id: 47, name: "Muhammed", meaning: "Hz. Muhammed", verses: 38 },
    { id: 48, name: "Fetih", meaning: "Fetih, Başarı", verses: 29 },
    { id: 49, name: "Hucurât", meaning: "Odalar", verses: 18 },
    { id: 50, name: "Kâf", meaning: "Kaf", verses: 45 },
    { id: 51, name: "Zâriyât", meaning: "Tozutup Savuranlar", verses: 60 },
    { id: 52, name: "Tûr", meaning: "Tur Dağı", verses: 49 },
    { id: 53, name: "Necm", meaning: "Yıldız", verses: 62 },
    { id: 54, name: "Kamer", meaning: "Ay", verses: 55 },
    { id: 55, name: "Rahmân", meaning: "Rahman", verses: 78 },
    { id: 56, name: "Vâkıa", meaning: "Olay", verses: 96 },
    { id: 57, name: "Hadîd", meaning: "Demir", verses: 29 },
    { id: 58, name: "Mücâdele", meaning: "Mücadele Eden Kadın", verses: 22 },
    { id: 59, name: "Haşr", meaning: "Toplanma", verses: 24 },
    { id: 60, name: "Mümtehine", meaning: "Sınanan Kadın", verses: 13 },
    { id: 61, name: "Saff", meaning: "Sıra", verses: 14 },
    { id: 62, name: "Cuma", meaning: "Cuma", verses: 11 },
    { id: 63, name: "Münâfikûn", meaning: "Münafıklar", verses: 11 },
    { id: 64, name: "Tegâbün", meaning: "Kar Karşılaşması", verses: 18 },
    { id: 65, name: "Talâk", meaning: "Boşanma", verses: 12 },
    { id: 66, name: "Tahrîm", meaning: "Haram Kılma", verses: 12 },
    { id: 67, name: "Mülk", meaning: "Hükümranlık", verses: 30 },
    { id: 68, name: "Kalem", meaning: "Kalem", verses: 52 },
    { id: 69, name: "Hâkka", meaning: "Gerçekleşen", verses: 52 },
    { id: 70, name: "Meâric", meaning: "Yükselme Yolları", verses: 44 },
    { id: 71, name: "Nûh", meaning: "Nuh Peygamber", verses: 28 },
    { id: 72, name: "Cin", meaning: "Cin", verses: 28 },
    { id: 73, name: "Müzzemmil", meaning: "Örtünan", verses: 20 },
    { id: 74, name: "Müddessir", meaning: "Bürünan", verses: 56 },
    { id: 75, name: "Kıyâmet", meaning: "Kıyamet", verses: 40 },
    { id: 76, name: "İnsân", meaning: "İnsan", verses: 31 },
    { id: 77, name: "Mürselât", meaning: "Gönderilenler", verses: 50 },
    { id: 78, name: "Nebe'", meaning: "Haber", verses: 40 },
    { id: 79, name: "Nâziât", meaning: "Söküp Çıkaranlar", verses: 46 },
    { id: 80, name: "Abese", meaning: "Yüz Ekşitti", verses: 42 },
    { id: 81, name: "Tekvîr", meaning: "Dürülme", verses: 29 },
    { id: 82, name: "İnfitâr", meaning: "Yarılma", verses: 19 },
    { id: 83, name: "Mutaffifîn", meaning: "Eksik Ölçenler", verses: 36 },
    { id: 84, name: "İnşikâk", meaning: "Yarılma", verses: 25 },
    { id: 85, name: "Bürûc", meaning: "Burçlar", verses: 22 },
    { id: 86, name: "Târık", meaning: "Gece Gelen", verses: 17 },
    { id: 87, name: "A'lâ", meaning: "En Yüce", verses: 19 },
    { id: 88, name: "Gâşiye", meaning: "Kaplayıp Bürüyan", verses: 26 },
    { id: 89, name: "Fecr", meaning: "Tan Yeri", verses: 30 },
    { id: 90, name: "Beled", meaning: "Şehir", verses: 20 },
    { id: 91, name: "Şems", meaning: "Güneş", verses: 15 },
    { id: 92, name: "Leyl", meaning: "Gece", verses: 21 },
    { id: 93, name: "Duhâ", meaning: "Kuşluk Vakti", verses: 11 },
    { id: 94, name: "İnşirâh", meaning: "Açılma, Ferahlama", verses: 8 },
    { id: 95, name: "Tîn", meaning: "İncir", verses: 8 },
    { id: 96, name: "Alak", meaning: "Kan Pıhtısı", verses: 19 },
    { id: 97, name: "Kadir", meaning: "Kadir Gecesi", verses: 5 },
    { id: 98, name: "Beyyine", meaning: "Açık Delil", verses: 8 },
    { id: 99, name: "Zilzâl", meaning: "Deprem", verses: 8 },
    { id: 100, name: "Âdiyât", meaning: "Koşan Atlar", verses: 11 },
    { id: 101, name: "Kâria", meaning: "Çarpan, Vuran", verses: 11 },
    { id: 102, name: "Tekâsür", meaning: "Çoklukla Övünme", verses: 8 },
    { id: 103, name: "Asr", meaning: "Zaman, Çağ", verses: 3 },
    { id: 104, name: "Hümeze", meaning: "Arkadan Çekiştiren", verses: 9 },
    { id: 105, name: "Fîl", meaning: "Fil", verses: 5 },
    { id: 106, name: "Kureyş", meaning: "Kureyş Kabilesi", verses: 4 },
    { id: 107, name: "Mâûn", meaning: "Yardım", verses: 7 },
    { id: 108, name: "Kevser", meaning: "Çok Hayır", verses: 3 },
    { id: 109, name: "Kâfirûn", meaning: "İnkarcılar", verses: 6 },
    { id: 110, name: "Nasr", meaning: "Yardım", verses: 3 },
    { id: 111, name: "Tebbet", meaning: "Kurusun", verses: 5 },
    { id: 112, name: "İhlâs", meaning: "Samimiyet", verses: 4 },
    { id: 113, name: "Felak", meaning: "Sabah", verses: 5 },
    { id: 114, name: "Nâs", meaning: "İnsanlar", verses: 6 }
];
